### ISSUE TITLE
Bad request error 

### ISSUE THREAD

**Issue by sushant12** [schneems/derailed_benchmarks#103]
When running `derailed exec perf:mem_over_time` I got the following err

```
PID: 7485
I, [2017-05-22T16:09:00.005495 #7485]  INFO -- : Started GET "/" for  at 2017-05-22 16:09:00 +0545
164.84375
I, [2017-05-22T16:09:00.039285 #7485]  INFO -- : Processing by ProjectsController#index as HTML
I, [2017-05-22T16:09:00.042417 #7485]  INFO -- : Redirected to http://www.example.org/
I, [2017-05-22T16:09:00.042492 #7485]  INFO -- : Filter chain halted as :force_www rendered or redirected
I, [2017-05-22T16:09:00.042615 #7485]  INFO -- : Completed 302 Found in 3ms (ActiveRecord: 0.0ms)
/home/sushant/.rvm/gems/ruby-2.3.1/gems/derailed_benchmarks-1.3.2/lib/derailed_benchmarks/tasks.rb:92:in `call_app': Bad request: <html><body>You are being <a href="http://www.example.org/">redirected</a>.</body></html> (RuntimeError)
	from /home/sushant/.rvm/gems/ruby-2.3.1/gems/derailed_benchmarks-1.3.2/lib/derailed_benchmarks/tasks.rb:174:in `block (3 levels) in <top (required)>'
	from /home/sushant/.rvm/gems/ruby-2.3.1/gems/derailed_benchmarks-1.3.2/lib/derailed_benchmarks/tasks.rb:173:in `times'
	from /home/sushant/.rvm/gems/ruby-2.3.1/gems/derailed_benchmarks-1.3.2/lib/derailed_benchmarks/tasks.rb:173:in `block (2 levels) in <top (required)>'
	from /home/sushant/.rvm/gems/ruby-2.3.1/gems/rake-12.0.0/lib/rake/task.rb:250:in `block in execute'
	from /home/sushant/.rvm/gems/ruby-2.3.1/gems/rake-12.0.0/lib/rake/task.rb:250:in `each'
	from /home/sushant/.rvm/gems/ruby-2.3.1/gems/rake-12.0.0/lib/rake/task.rb:250:in `execute'
	from /home/sushant/.rvm/gems/ruby-2.3.1/gems/rake-12.0.0/lib/rake/task.rb:194:in `block in invoke_with_call_chain'
	from /home/sushant/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
	from /home/sushant/.rvm/gems/ruby-2.3.1/gems/rake-12.0.0/lib/rake/task.rb:187:in `invoke_with_call_chain'
	from /home/sushant/.rvm/gems/ruby-2.3.1/gems/rake-12.0.0/lib/rake/task.rb:180:in `invoke'
	from /home/sushant/.rvm/gems/ruby-2.3.1/gems/derailed_benchmarks-1.3.2/bin/derailed:41:in `exec'
	from /home/sushant/.rvm/gems/ruby-2.3.1/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	from /home/sushant/.rvm/gems/ruby-2.3.1/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	from /home/sushant/.rvm/gems/ruby-2.3.1/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	from /home/sushant/.rvm/gems/ruby-2.3.1/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
	from /home/sushant/.rvm/gems/ruby-2.3.1/gems/derailed_benchmarks-1.3.2/bin/derailed:92:in `<top (required)>'
	from /home/sushant/.rvm/gems/ruby-2.3.1/bin/derailed:22:in `load'
	from /home/sushant/.rvm/gems/ruby-2.3.1/bin/derailed:22:in `<main>'
	from /home/sushant/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
	from /home/sushant/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'

```

**Comment by benoittgt** [comment]
This is related to your app. See `Filter chain halted as :force_www rendered or redirected`

**Comment by sushant12** [comment]
@benoittgt oh ya you are right. Thanks man :)
