### ISSUE TITLE
Multiple devise Models

### ISSUE THREAD

**Issue by silva96** [schneems/derailed_benchmarks#107]
Hi, I have an app which was 3 authenticable Models
`User`, `Agency`, `AdminUser`

I'm failing to perform the benchmarks.
when calling `RAILS_ENV=development  USE_AUTH=true bundle exec derailed exec perf:mem_over_time`

```

Booting: development
Endpoint: "/"
Auth: true
/Users/benja/.rvm/gems/ruby-2.4.0@rails_5/gems/derailed_benchmarks-1.3.2/lib/derailed_benchmarks/tasks.rb:72: warning: already initialized constant DERAILED_APP
/Users/benja/.rvm/gems/ruby-2.4.0@rails_5/gems/derailed_benchmarks-1.3.2/lib/derailed_benchmarks/tasks.rb:23: warning: previous definition of DERAILED_APP was here
PID: 17858
160.21875
/Users/benja/dev/ibilbidea/perf.rake:15:in `call': undefined local variable or method `current_user' for #<MyCustomAuth:0x007fc159f4c028> (NameError)
	from /Users/benja/.rvm/gems/ruby-2.4.0@rails_5/gems/rack-2.0.1/lib/rack/mock.rb:74:in `request'
	from /Users/benja/.rvm/gems/ruby-2.4.0@rails_5/gems/rack-2.0.1/lib/rack/mock.rb:56:in `get'
	from /Users/benja/.rvm/gems/ruby-2.4.0@rails_5/gems/derailed_benchmarks-1.3.2/lib/derailed_benchmarks/tasks.rb:91:in `call_app'
	from /Users/benja/.rvm/gems/ruby-2.4.0@rails_5/gems/derailed_benchmarks-1.3.2/lib/derailed_benchmarks/tasks.rb:174:in `block (3 levels) in <top (required)>'
	from /Users/benja/.rvm/gems/ruby-2.4.0@rails_5/gems/derailed_benchmarks-1.3.2/lib/derailed_benchmarks/tasks.rb:173:in `times'
	from /Users/benja/.rvm/gems/ruby-2.4.0@rails_5/gems/derailed_benchmarks-1.3.2/lib/derailed_benchmarks/tasks.rb:173:in `block (2 levels) in <top (required)>'
	from /Users/benja/.rvm/gems/ruby-2.4.0@global/gems/rake-12.0.0/lib/rake/task.rb:250:in `block in execute'
	from /Users/benja/.rvm/gems/ruby-2.4.0@global/gems/rake-12.0.0/lib/rake/task.rb:250:in `each'
	from /Users/benja/.rvm/gems/ruby-2.4.0@global/gems/rake-12.0.0/lib/rake/task.rb:250:in `execute'
	from /Users/benja/.rvm/gems/ruby-2.4.0@rails_5/gems/airbrake-6.0.0/lib/airbrake/rake/task_ext.rb:19:in `execute'
	from /Users/benja/.rvm/gems/ruby-2.4.0@global/gems/rake-12.0.0/lib/rake/task.rb:194:in `block in invoke_with_call_chain'
	from /Users/benja/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
	from /Users/benja/.rvm/gems/ruby-2.4.0@global/gems/rake-12.0.0/lib/rake/task.rb:187:in `invoke_with_call_chain'
	from /Users/benja/.rvm/gems/ruby-2.4.0@global/gems/rake-12.0.0/lib/rake/task.rb:180:in `invoke'
	from /Users/benja/.rvm/gems/ruby-2.4.0@rails_5/gems/derailed_benchmarks-1.3.2/bin/derailed:41:in `exec'
	from /Users/benja/.rvm/gems/ruby-2.4.0@rails_5/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	from /Users/benja/.rvm/gems/ruby-2.4.0@rails_5/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/benja/.rvm/gems/ruby-2.4.0@rails_5/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	from /Users/benja/.rvm/gems/ruby-2.4.0@rails_5/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
	from /Users/benja/.rvm/gems/ruby-2.4.0@rails_5/gems/derailed_benchmarks-1.3.2/bin/derailed:92:in `<top (required)>'
	from /Users/benja/.rvm/gems/ruby-2.4.0@rails_5/bin/derailed:22:in `load'
	from /Users/benja/.rvm/gems/ruby-2.4.0@rails_5/bin/derailed:22:in `<main>'
	from /Users/benja/.rvm/gems/ruby-2.4.0@rails_5/bin/ruby_executable_hooks:15:in `eval'
	from /Users/benja/.rvm/gems/ruby-2.4.0@rails_5/bin/ruby_executable_hooks:15:in `<main>'
```

I tried this following perf.rake

```
class MyCustomAuth < DerailedBenchmarks::AuthHelper
  def setup
    # initialize code here
    require 'devise'
    require 'warden'
    extend ::Warden::Test::Helpers
    extend ::Devise::TestHelpers
    Warden.test_mode!
  end

  def call(env)
    # log something in on each request
    login_as(User.last, scope: :user)
    login_as(Agency.last, scope: :agency)
    login_as(AdminUser.last, scope: :admin_user)
    app.call(env)
  end
end

DerailedBenchmarks.auth = MyCustomAuth.new
```

what I'm missing?

best regards

**Comment by schneems** [comment]
It looks like it expects `MyCustomAuth` to have a `current_user` method? That seems off.
