### ISSUE TITLE
airbrake causing problems

### ISSUE THREAD

**Issue by tansaku** [schneems/derailed_benchmarks#110]
Awesome project!

I'm trying to hunt down memory leaks, and I had trouble starting `perf:mem_over_time` until I added various Airbrake keys, but then I'm still getting an error (testing our Rails app)

```
→ AIRBRAKE_PROJECT_ID=6 AIRBRAKE_API_KEY=XXXX bundle exec derailed exec perf:mem_over_time
Booting: production
Endpoint: "/"
/Users/tansaku/.rvm/gems/ruby-2.3.1/gems/derailed_benchmarks-1.3.2/lib/derailed_benchmarks/tasks.rb:72: warning: already initialized constant DERAILED_APP
/Users/tansaku/.rvm/gems/ruby-2.3.1/gems/derailed_benchmarks-1.3.2/lib/derailed_benchmarks/tasks.rb:23: warning: previous definition of DERAILED_APP was here
PID: 79590
211.39453125
/Users/tansaku/.rvm/gems/ruby-2.3.1/gems/derailed_benchmarks-1.3.2/lib/derailed_benchmarks/tasks.rb:92:in `call_app': Bad request:  (RuntimeError)
	from /Users/tansaku/.rvm/gems/ruby-2.3.1/gems/derailed_benchmarks-1.3.2/lib/derailed_benchmarks/tasks.rb:174:in `block (3 levels) in <top (required)>'
	from /Users/tansaku/.rvm/gems/ruby-2.3.1/gems/derailed_benchmarks-1.3.2/lib/derailed_benchmarks/tasks.rb:173:in `times'
	from /Users/tansaku/.rvm/gems/ruby-2.3.1/gems/derailed_benchmarks-1.3.2/lib/derailed_benchmarks/tasks.rb:173:in `block (2 levels) in <top (required)>'
	from /Users/tansaku/.rvm/gems/ruby-2.3.1/gems/rake-12.1.0/lib/rake/task.rb:251:in `block in execute'
	from /Users/tansaku/.rvm/gems/ruby-2.3.1/gems/rake-12.1.0/lib/rake/task.rb:251:in `each'
	from /Users/tansaku/.rvm/gems/ruby-2.3.1/gems/rake-12.1.0/lib/rake/task.rb:251:in `execute'
	from /Users/tansaku/.rvm/gems/ruby-2.3.1/gems/airbrake-6.0.0/lib/airbrake/rake/task_ext.rb:19:in `execute'
	from /Users/tansaku/.rvm/gems/ruby-2.3.1/gems/rake-12.1.0/lib/rake/task.rb:195:in `block in invoke_with_call_chain'
	from /Users/tansaku/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
	from /Users/tansaku/.rvm/gems/ruby-2.3.1/gems/rake-12.1.0/lib/rake/task.rb:188:in `invoke_with_call_chain'
	from /Users/tansaku/.rvm/gems/ruby-2.3.1/gems/rake-12.1.0/lib/rake/task.rb:181:in `invoke'
	from /Users/tansaku/.rvm/gems/ruby-2.3.1/gems/derailed_benchmarks-1.3.2/bin/derailed:41:in `exec'
	from /Users/tansaku/.rvm/gems/ruby-2.3.1/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	from /Users/tansaku/.rvm/gems/ruby-2.3.1/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/tansaku/.rvm/gems/ruby-2.3.1/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	from /Users/tansaku/.rvm/gems/ruby-2.3.1/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
	from /Users/tansaku/.rvm/gems/ruby-2.3.1/gems/derailed_benchmarks-1.3.2/bin/derailed:92:in `<top (required)>'
	from /Users/tansaku/.rvm/gems/ruby-2.3.1/bin/derailed:23:in `load'
	from /Users/tansaku/.rvm/gems/ruby-2.3.1/bin/derailed:23:in `<main>'
	from /Users/tansaku/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
	from /Users/tansaku/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'
```

The full project is https://github.com/AgileVentures/WebsiteOne/ - maybe I just turn off Airbrake - or might it be something else ...?

**Comment by tansaku** [comment]
hmm, even with airbrake initialization code commented out I get the same error, also with airbrake in the stack trace ...

**Comment by tansaku** [comment]
have removed airbrake gem and now the error looks like this:

```
→ AIRBRAKE_PROJECT_ID=6 AIRBRAKE_API_KEY=XXXX bundle exec derailed exec perf:mem_over_time
Booting: production
Endpoint: "/"
/Users/tansaku/.rvm/gems/ruby-2.3.1/gems/derailed_benchmarks-1.3.2/lib/derailed_benchmarks/tasks.rb:72: warning: already initialized constant DERAILED_APP
/Users/tansaku/.rvm/gems/ruby-2.3.1/gems/derailed_benchmarks-1.3.2/lib/derailed_benchmarks/tasks.rb:23: warning: previous definition of DERAILED_APP was here
PID: 79747
212.7421875
/Users/tansaku/.rvm/gems/ruby-2.3.1/gems/derailed_benchmarks-1.3.2/lib/derailed_benchmarks/tasks.rb:92:in `call_app': Bad request:  (RuntimeError)
	from /Users/tansaku/.rvm/gems/ruby-2.3.1/gems/derailed_benchmarks-1.3.2/lib/derailed_benchmarks/tasks.rb:174:in `block (3 levels) in <top (required)>'
	from /Users/tansaku/.rvm/gems/ruby-2.3.1/gems/derailed_benchmarks-1.3.2/lib/derailed_benchmarks/tasks.rb:173:in `times'
	from /Users/tansaku/.rvm/gems/ruby-2.3.1/gems/derailed_benchmarks-1.3.2/lib/derailed_benchmarks/tasks.rb:173:in `block (2 levels) in <top (required)>'
	from /Users/tansaku/.rvm/gems/ruby-2.3.1/gems/rake-12.1.0/lib/rake/task.rb:251:in `block in execute'
	from /Users/tansaku/.rvm/gems/ruby-2.3.1/gems/rake-12.1.0/lib/rake/task.rb:251:in `each'
	from /Users/tansaku/.rvm/gems/ruby-2.3.1/gems/rake-12.1.0/lib/rake/task.rb:251:in `execute'
	from /Users/tansaku/.rvm/gems/ruby-2.3.1/gems/rake-12.1.0/lib/rake/task.rb:195:in `block in invoke_with_call_chain'
	from /Users/tansaku/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
	from /Users/tansaku/.rvm/gems/ruby-2.3.1/gems/rake-12.1.0/lib/rake/task.rb:188:in `invoke_with_call_chain'
	from /Users/tansaku/.rvm/gems/ruby-2.3.1/gems/rake-12.1.0/lib/rake/task.rb:181:in `invoke'
	from /Users/tansaku/.rvm/gems/ruby-2.3.1/gems/derailed_benchmarks-1.3.2/bin/derailed:41:in `exec'
	from /Users/tansaku/.rvm/gems/ruby-2.3.1/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	from /Users/tansaku/.rvm/gems/ruby-2.3.1/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/tansaku/.rvm/gems/ruby-2.3.1/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	from /Users/tansaku/.rvm/gems/ruby-2.3.1/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
	from /Users/tansaku/.rvm/gems/ruby-2.3.1/gems/derailed_benchmarks-1.3.2/bin/derailed:92:in `<top (required)>'
	from /Users/tansaku/.rvm/gems/ruby-2.3.1/bin/derailed:23:in `load'
	from /Users/tansaku/.rvm/gems/ruby-2.3.1/bin/derailed:23:in `<main>'
	from /Users/tansaku/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
	from /Users/tansaku/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'
```

any ideas?

many thanks in advance

**Comment by tansaku** [comment]
I note that I've turned off "config.force_ssl = false" and it now seems to be working :-)
