### ISSUE TITLE
Error running outside an Rails app

### ISSUE THREAD

**Issue by brauliobo** [schneems/derailed_benchmarks#123]
`task/perf.rake` is filled with:
```ruby
namespace :perf do                                                                                                                                                                           
  task :rack_load do                                                                                                                                                                         
    MyTask.new.run                                                                                                                      
  end                                                                                                                                                                                        
end   
```

```
~/P/o/scheduler ❯❯❯ derailed exec perf:objects                                                                                                                                 ⏎master ✭ ✱ ◼
You're not using Rails
You need to tell derailed how to boot your app
In your perf.rake add:

namespace :perf do
  task :rack_load do
    # DERAILED_APP = your code here
  end
end
Endpoint: "/"
/home/braulio/.rvm/gems/ruby-2.4.2/gems/derailed_benchmarks-1.3.4/lib/derailed_benchmarks/tasks.rb:71:in `block (3 levels) in <top (required)>': undefined method `starts_with?' for "ANT_HOME":String (NoMethodError)
Did you mean?  start_with?
        from /home/braulio/.rvm/gems/ruby-2.4.2/gems/derailed_benchmarks-1.3.4/lib/derailed_benchmarks/tasks.rb:71:in `select'                                                              
        from /home/braulio/.rvm/gems/ruby-2.4.2/gems/derailed_benchmarks-1.3.4/lib/derailed_benchmarks/tasks.rb:71:in `block (2 levels) in <top (required)>'                                
        from /home/braulio/.rvm/gems/ruby-2.4.2/gems/rake-12.3.0/lib/rake/task.rb:251:in `block in execute'                                                                                 
        from /home/braulio/.rvm/gems/ruby-2.4.2/gems/rake-12.3.0/lib/rake/task.rb:251:in `each'                                                                                             
        from /home/braulio/.rvm/gems/ruby-2.4.2/gems/rake-12.3.0/lib/rake/task.rb:251:in `execute'                                                                                          
        from /home/braulio/.rvm/gems/ruby-2.4.2/gems/rake-12.3.0/lib/rake/task.rb:195:in `block in invoke_with_call_chain'                                                                  
        from /home/braulio/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'                                                                                        
        from /home/braulio/.rvm/gems/ruby-2.4.2/gems/rake-12.3.0/lib/rake/task.rb:188:in `invoke_with_call_chain'                                                                           
        from /home/braulio/.rvm/gems/ruby-2.4.2/gems/rake-12.3.0/lib/rake/task.rb:217:in `block in invoke_prerequisites'                                                                    
        from /home/braulio/.rvm/gems/ruby-2.4.2/gems/rake-12.3.0/lib/rake/task.rb:215:in `each'                                                                                             
        from /home/braulio/.rvm/gems/ruby-2.4.2/gems/rake-12.3.0/lib/rake/task.rb:215:in `invoke_prerequisites'                                                                             
        from /home/braulio/.rvm/gems/ruby-2.4.2/gems/rake-12.3.0/lib/rake/task.rb:194:in `block in invoke_with_call_chain'                                                                  
        from /home/braulio/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'                                                                                        
        from /home/braulio/.rvm/gems/ruby-2.4.2/gems/rake-12.3.0/lib/rake/task.rb:188:in `invoke_with_call_chain'                                                                           
        from /home/braulio/.rvm/gems/ruby-2.4.2/gems/rake-12.3.0/lib/rake/task.rb:181:in `invoke'                                                                                           
        from /home/braulio/.rvm/gems/ruby-2.4.2/gems/derailed_benchmarks-1.3.4/bin/derailed:41:in `exec'                                                                                    
        from /home/braulio/.rvm/gems/ruby-2.4.2/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'                                                                                            
        from /home/braulio/.rvm/gems/ruby-2.4.2/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'                                                                             
        from /home/braulio/.rvm/gems/ruby-2.4.2/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'                                                                                              
        from /home/braulio/.rvm/gems/ruby-2.4.2/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'                                                                                            
        from /home/braulio/.rvm/gems/ruby-2.4.2/gems/derailed_benchmarks-1.3.4/bin/derailed:92:in `<top (required)>'                                                                        
        from /home/braulio/.rvm/gems/ruby-2.4.2/bin/derailed:23:in `load'
        from /home/braulio/.rvm/gems/ruby-2.4.2/bin/derailed:23:in `<main>'
        from /home/braulio/.rvm/gems/ruby-2.4.2/bin/ruby_executable_hooks:15:in `eval'
        from /home/braulio/.rvm/gems/ruby-2.4.2/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by k0kubun** [comment]
It seems to depend on ActiveSupport https://github.com/rails/rails/blob/cfb1e4dfd8813d3d5c75a15a750b3c53eebdea65/activesupport/lib/active_support/core_ext/string/starts_ends_with.rb#L4
