### ISSUE TITLE
`SystemStackError` when running `derailed exec perf:mem`

### ISSUE THREAD

**Issue by cesarizu** [schneems/derailed_benchmarks#129]
Hi, when I run `derailed exec perf:mem` I get the following error, what can I do?

```
Booting: production                                                                                                                                                                [9603/28895]
Traceback (most recent call last):                                                                                                                                                             
        9638: from /home/user/.rvm/gems/ruby-2.6.3@project/bin/ruby_executable_hooks:24:in `<main>'                                                                                         
        9637: from /home/user/.rvm/gems/ruby-2.6.3@project/bin/ruby_executable_hooks:24:in `eval'                                                                                           
        9636: from /home/user/.rvm/gems/ruby-2.6.3@project/bin/derailed:23:in `<main>'                                                                                                      
        9635: from /home/user/.rvm/gems/ruby-2.6.3@project/bin/derailed:23:in `load'                                                                                                        
        9634: from /home/user/.rvm/gems/ruby-2.6.3@project/gems/derailed_benchmarks-1.3.5/bin/derailed:92:in `<top (required)>'                                                             
        9633: from /home/user/.rvm/gems/ruby-2.6.3@project/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'                                                                                 
        9632: from /home/user/.rvm/gems/ruby-2.6.3@project/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'                                                                                   
        9631: from /home/user/.rvm/gems/ruby-2.6.3@project/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'                                                                  
        9630: from /home/user/.rvm/gems/ruby-2.6.3@project/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'                                                                                 
        9629: from /home/user/.rvm/gems/ruby-2.6.3@project/gems/derailed_benchmarks-1.3.5/bin/derailed:41:in `exec'                                                                         
        9628: from /home/user/.rvm/rubies/ruby-2.6.3/lib64/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/task.rb:183:in `invoke'                                                                  
        9627: from /home/user/.rvm/rubies/ruby-2.6.3/lib64/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/task.rb:194:in `invoke_with_call_chain'                                                  
        9626: from /home/user/.rvm/rubies/ruby-2.6.3/lib64/ruby/2.6.0/monitor.rb:230:in `mon_synchronize'                                                                                     
        9625: from /home/user/.rvm/rubies/ruby-2.6.3/lib64/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/task.rb:213:in `block in invoke_with_call_chain'                                         
        9624: from /home/user/.rvm/rubies/ruby-2.6.3/lib64/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/task.rb:236:in `invoke_prerequisites'                                                    
        9623: from /home/user/.rvm/rubies/ruby-2.6.3/lib64/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/task.rb:236:in `each'                                                                    
        9622: from /home/user/.rvm/rubies/ruby-2.6.3/lib64/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/task.rb:238:in `block in invoke_prerequisites'                                           
        9621: from /home/user/.rvm/rubies/ruby-2.6.3/lib64/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/task.rb:194:in `invoke_with_call_chain'                                                  
        9620: from /home/user/.rvm/rubies/ruby-2.6.3/lib64/ruby/2.6.0/monitor.rb:230:in `mon_synchronize'                                                                                     
        9619: from /home/user/.rvm/rubies/ruby-2.6.3/lib64/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/task.rb:214:in `block in invoke_with_call_chain'                                         
        9618: from /home/user/.rvm/rubies/ruby-2.6.3/lib64/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/task.rb:273:in `execute'                                                                 
        9617: from /home/user/.rvm/rubies/ruby-2.6.3/lib64/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/task.rb:273:in `each'
        9616: from /home/user/.rvm/rubies/ruby-2.6.3/lib64/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/task.rb:273:in `block in execute'
        9615: from /home/user/.rvm/gems/ruby-2.6.3@project/gems/derailed_benchmarks-1.3.5/lib/derailed_benchmarks/tasks.rb:60:in `block (2 levels) in <top (required)>'
        9614: from /home/user/.rvm/rubies/ruby-2.6.3/lib64/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/task.rb:183:in `invoke'
        9613: from /home/user/.rvm/rubies/ruby-2.6.3/lib64/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/task.rb:194:in `invoke_with_call_chain'
        9612: from /home/user/.rvm/rubies/ruby-2.6.3/lib64/ruby/2.6.0/monitor.rb:230:in `mon_synchronize'
        9611: from /home/user/.rvm/rubies/ruby-2.6.3/lib64/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/task.rb:214:in `block in invoke_with_call_chain'
        9610: from /home/user/.rvm/rubies/ruby-2.6.3/lib64/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/task.rb:273:in `execute'
        9609: from /home/user/.rvm/rubies/ruby-2.6.3/lib64/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/task.rb:273:in `each'
        9608: from /home/user/.rvm/rubies/ruby-2.6.3/lib64/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/task.rb:273:in `block in execute'
        9607: from /home/user/.rvm/gems/ruby-2.6.3@project/gems/derailed_benchmarks-1.3.5/lib/derailed_benchmarks/tasks.rb:19:in `block (2 levels) in <top (required)>'
        9606: from /home/user/.rvm/gems/ruby-2.6.3@project/gems/derailed_benchmarks-1.3.5/lib/derailed_benchmarks/core_ext/kernel_require.rb:16:in `require'
        9605: from /home/user/.rvm/gems/ruby-2.6.3@project/gems/derailed_benchmarks-1.3.5/lib/derailed_benchmarks/core_ext/kernel_require.rb:63:in `block in <top (required)>'
        9604: from /home/user/.rvm/gems/ruby-2.6.3@project/gems/derailed_benchmarks-1.3.5/lib/derailed_benchmarks/core_ext/kernel_require.rb:49:in `measure_memory_impact'
        9603: from /home/user/.rvm/gems/ruby-2.6.3@project/gems/derailed_benchmarks-1.3.5/lib/derailed_benchmarks/core_ext/kernel_require.rb:63:in `block (2 levels) in <top (required)>'
        9602: from /home/user/.rvm/gems/ruby-2.6.3@project/gems/derailed_benchmarks-1.3.5/lib/derailed_benchmarks/core_ext/kernel_require.rb:63:in `require'
        9601: from /home/user/src/govsciences/project/config/application.rb:3:in `<top (required)>'
        9600: from /home/user/src/govsciences/project/config/application.rb:3:in `require_relative'
        9599: from /home/user/src/govsciences/project/config/boot.rb:6:in `<top (required)>' 
        9598: from /home/user/.rvm/gems/ruby-2.6.3@project/gems/derailed_benchmarks-1.3.5/lib/derailed_benchmarks/core_ext/kernel_require.rb:16:in `require'
        9597: from /home/user/.rvm/gems/ruby-2.6.3@project/gems/derailed_benchmarks-1.3.5/lib/derailed_benchmarks/core_ext/kernel_require.rb:63:in `block in <top (required)>'
        9596: from /home/user/.rvm/gems/ruby-2.6.3@project/gems/derailed_benchmarks-1.3.5/lib/derailed_benchmarks/core_ext/kernel_require.rb:49:in `measure_memory_impact'
        9595: from /home/user/.rvm/gems/ruby-2.6.3@project/gems/derailed_benchmarks-1.3.5/lib/derailed_benchmarks/core_ext/kernel_require.rb:63:in `block (2 levels) in <top (required)>'
        9594: from /home/user/.rvm/gems/ruby-2.6.3@project/gems/derailed_benchmarks-1.3.5/lib/derailed_benchmarks/core_ext/kernel_require.rb:63:in `require'
        9593: from /home/user/.rvm/gems/ruby-2.6.3@project/gems/bootsnap-1.4.3/lib/bootsnap/setup.rb:27:in `<top (required)>'
        9592: from /home/user/.rvm/gems/ruby-2.6.3@project/gems/bootsnap-1.4.3/lib/bootsnap.rb:24:in `setup'
        9591: from /home/user/.rvm/gems/ruby-2.6.3@project/gems/bootsnap-1.4.3/lib/bootsnap/load_path_cache.rb:47:in `setup'
        9590: from /home/user/.rvm/gems/ruby-2.6.3@project/gems/bootsnap-1.4.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:48:in `require_relative'
        9589: from /home/user/.rvm/gems/ruby-2.6.3@project/gems/bootsnap-1.4.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        9588: from /home/user/.rvm/gems/ruby-2.6.3@project/gems/bootsnap-1.4.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
        9587: from /home/user/.rvm/gems/ruby-2.6.3@project/gems/bootsnap-1.4.3/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
        9586: from /home/user/.rvm/gems/ruby-2.6.3@project/gems/bootsnap-1.4.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
        9585: from /home/user/.rvm/gems/ruby-2.6.3@project/gems/derailed_benchmarks-1.3.5/lib/derailed_benchmarks/core_ext/kernel_require.rb:16:in `require'
        9584: from /home/user/.rvm/gems/ruby-2.6.3@project/gems/bootsnap-1.4.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        9583: from /home/user/.rvm/gems/ruby-2.6.3@project/gems/bootsnap-1.4.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
        9582: from /home/user/.rvm/gems/ruby-2.6.3@project/gems/bootsnap-1.4.3/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'

================== [omitted 1000s of repeated lines] ======================================

          11: from /home/user/.rvm/gems/ruby-2.6.3@project/gems/bootsnap-1.4.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
          10: from /home/user/.rvm/gems/ruby-2.6.3@project/gems/derailed_benchmarks-1.3.5/lib/derailed_benchmarks/core_ext/kernel_require.rb:16:in `require'
           9: from /home/user/.rvm/gems/ruby-2.6.3@project/gems/bootsnap-1.4.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
           8: from /home/user/.rvm/gems/ruby-2.6.3@project/gems/bootsnap-1.4.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
           7: from /home/user/.rvm/gems/ruby-2.6.3@project/gems/bootsnap-1.4.3/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
           6: from /home/user/.rvm/gems/ruby-2.6.3@project/gems/bootsnap-1.4.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
           5: from /home/user/.rvm/gems/ruby-2.6.3@project/gems/derailed_benchmarks-1.3.5/lib/derailed_benchmarks/core_ext/kernel_require.rb:16:in `require'
           4: from /home/user/.rvm/gems/ruby-2.6.3@project/gems/bootsnap-1.4.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
           3: from /home/user/.rvm/gems/ruby-2.6.3@project/gems/bootsnap-1.4.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
           2: from /home/user/.rvm/gems/ruby-2.6.3@project/gems/bootsnap-1.4.3/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
           1: from /home/user/.rvm/gems/ruby-2.6.3@project/gems/bootsnap-1.4.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
/home/user/.rvm/gems/ruby-2.6.3@project/gems/derailed_benchmarks-1.3.5/lib/derailed_benchmarks/core_ext/kernel_require.rb:16:in `require': stack level too deep (SystemStackError)
```

**Comment by cesarizu** [comment]
If I increase the stack size with `RUBY_THREAD_VM_STACK_SIZE` or `ulimit` the error continues, the stack only gets larger.

**Comment by ispyropoulos** [comment]
I have this problem as well. Any clues @schneems? Thanks 🙏

**Comment by maayannaveh** [comment]
Same here +1

**Comment by noragrossman** [comment]
Same here! For me it only occurs when testing certain endpoints... some endpoints are fine and others cause this error.

**Comment by schneems** [comment]
Does anyone have an https://codetriage.com/example_app that they can give me so I can see this error for myself?

**Comment by engwan** [comment]
I created a PR for this: https://github.com/schneems/derailed_benchmarks/pull/170

Can you test if this fixes it for you?
