### ISSUE TITLE
syntax error, unexpected keyword_ensure

### ISSUE THREAD

**Issue by StephenTurley** [schneems/derailed_benchmarks#154]
Any exec task that  that I run throws this error. Using ruby-2.4.6 on a Mac. 

```
bundle exec derailed exec --help
/Users/stephen.turley/.rvm/gems/ruby-2.4.6/gems/derailed_benchmarks-1.4.1/bin/derailed:30:in `require': /Users/stephen.turley/.rvm/gems/ruby-2.4.6/gems/derailed_benchmarks-1.4.1/lib/derailed_benchmarks/tasks.rb:70: syntax error, unexpected keyword_ensure, expecting keyword_end (SyntaxError)
  ensure
        ^
/Users/stephen.turley/.rvm/gems/ruby-2.4.6/gems/derailed_benchmarks-1.4.1/lib/derailed_benchmarks/tasks.rb:256: syntax error, unexpected keyword_end, expecting end-of-input
        from /Users/stephen.turley/.rvm/gems/ruby-2.4.6/gems/derailed_benchmarks-1.4.1/bin/derailed:30:in `exec'
        from /Users/stephen.turley/.rvm/gems/ruby-2.4.6/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
        from /Users/stephen.turley/.rvm/gems/ruby-2.4.6/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
        from /Users/stephen.turley/.rvm/gems/ruby-2.4.6/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
        from /Users/stephen.turley/.rvm/gems/ruby-2.4.6/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
        from /Users/stephen.turley/.rvm/gems/ruby-2.4.6/gems/derailed_benchmarks-1.4.1/bin/derailed:93:in `<top (required)>'
        from /Users/stephen.turley/.rvm/gems/ruby-2.4.6/bin/derailed:23:in `load'
        from /Users/stephen.turley/.rvm/gems/ruby-2.4.6/bin/derailed:23:in `<main>'
        from /Users/stephen.turley/.rvm/gems/ruby-2.4.6/bin/ruby_executable_hooks:24:in `eval'
        from /Users/stephen.turley/.rvm/gems/ruby-2.4.6/bin/ruby_executable_hooks:24:in `<main>'
```

**Comment by jchan172** [comment]
I'm getting a similar issue. 

```
bundle exec derailed exec --help
/usr/local/bundle/gems/derailed_benchmarks-1.4.0/bin/derailed:30:in `require': /usr/local/bundle/gems/derailed_benchmarks-1.4.0/lib/derailed_benchmarks/tasks.rb:70: syntax error, unexpected keyword_ensure, expecting keyword_end (SyntaxError)
```

**Comment by schneems** [comment]
This is fixed on HEAD i believe
