### ISSUE TITLE
update ruby version requirements (ruby >= 2.3  for 1.6.0, ruby >= 2.4 for 1.7.0)

### ISSUE THREAD

**Issue by MathieuDerelle** [schneems/derailed_benchmarks#176]
cant launch this gem

```
$ bundle exec derailed bundle:mem
bundler: failed to load command: derailed (/Users/mathieu/.rvm/gems/ruby-2.2.9/bin/derailed)
NoMethodError: undefined method `+@' for "TOP: 102.4609 MiB":String
  /Users/mathieu/.rvm/gems/ruby-2.2.9/gems/derailed_benchmarks-1.6.0/lib/derailed_benchmarks/require_tree.rb:43:in `to_string'
  /Users/mathieu/.rvm/gems/ruby-2.2.9/gems/derailed_benchmarks-1.6.0/lib/derailed_benchmarks/require_tree.rb:58:in `print_sorted_children'
  /Users/mathieu/.rvm/gems/ruby-2.2.9/gems/derailed_benchmarks-1.6.0/lib/derailed_benchmarks/core_ext/kernel_require.rb:93:in `print_sorted_children'
  /Users/mathieu/.rvm/gems/ruby-2.2.9/gems/derailed_benchmarks-1.6.0/bin/derailed:70:in `block in <class:DerailedBenchmarkCLI>'
  /Users/mathieu/.rvm/gems/ruby-2.2.9/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
  /Users/mathieu/.rvm/gems/ruby-2.2.9/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
  /Users/mathieu/.rvm/gems/ruby-2.2.9/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
  /Users/mathieu/.rvm/gems/ruby-2.2.9/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
  /Users/mathieu/.rvm/gems/ruby-2.2.9/gems/derailed_benchmarks-1.6.0/bin/derailed:93:in `<top (required)>'
  /Users/mathieu/.rvm/gems/ruby-2.2.9/bin/derailed:23:in `load'
  /Users/mathieu/.rvm/gems/ruby-2.2.9/bin/derailed:23:in `<top (required)>'
```

ruby 2.2.9 / rails 3.2.22.5

**Comment by MathieuDerelle** [comment]
method `+@' is present in ruby [2.3.0](https://ruby-doc.org/core-2.3.0/String.html#method-i-2B-40) but not for ruby [2.2.x](https://ruby-doc.org/core-2.2.10/String.html#method-i-2B-40)

you need to update your ruby version requirements

**Comment by MathieuDerelle** [comment]
version 1.7.0 even require ruby 2.4

```
Bundler could not find compatible versions for gem "ruby":
  In Gemfile:
    ruby (~> 2.2.9.0)

    derailed_benchmarks was resolved to 1.7.0, which depends on
      unicode_plot (>= 0.0.4, < 1.0.0) was resolved to 0.0.4, which depends on
        enumerable-statistics (>= 2.0.1) was resolved to 2.0.1, which depends on
          ruby (>= 2.4)
```

**Comment by schneems** [comment]
Good news. I managed to get support to Ruby 2.2+. I'm now testing it you can see #177 for the required changes. I'll cut a new version soon.

**Comment by schneems** [comment]
1.8.0 is out now try it out
