### ISSUE TITLE
DeadEnd Internal error

### ISSUE THREAD

**Issue by josegrad** [schneems/derailed_benchmarks#191]
Hi,

Any ideas how to solve this?

```
bundle exec derailed bundle:mem development    
Traceback (most recent call last):
	13: from /Users/jgd/.rvm/gems/ruby-2.5.7@rails5.1.7/bin/ruby_executable_hooks:24:in `<main>'
	12: from /Users/jgd/.rvm/gems/ruby-2.5.7@rails5.1.7/bin/ruby_executable_hooks:24:in `eval'
	11: from /Users/jgd/.rvm/gems/ruby-2.5.7@rails5.1.7/bin/derailed:23:in `<main>'
	10: from /Users/jgd/.rvm/gems/ruby-2.5.7@rails5.1.7/bin/derailed:23:in `load'
	 9: from /Users/jgd/.rvm/gems/ruby-2.5.7@rails5.1.7/gems/derailed_benchmarks-2.0.1/bin/derailed:93:in `<top (required)>'
	 8: from /Users/jgd/.rvm/gems/ruby-2.5.7@rails5.1.7/gems/thor-1.1.0/lib/thor/base.rb:485:in `start'
	 7: from /Users/jgd/.rvm/gems/ruby-2.5.7@rails5.1.7/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
	 6: from /Users/jgd/.rvm/gems/ruby-2.5.7@rails5.1.7/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
	 5: from /Users/jgd/.rvm/gems/ruby-2.5.7@rails5.1.7/gems/thor-1.1.0/lib/thor/command.rb:20:in `run'
	 4: from /Users/jgd/.rvm/gems/ruby-2.5.7@rails5.1.7/gems/thor-1.1.0/lib/thor/command.rb:36:in `rescue in run'
	 3: from /Users/jgd/.rvm/gems/ruby-2.5.7@rails5.1.7/gems/thor-1.1.0/lib/thor/command.rb:114:in `handle_no_method_error?'
	 2: from /Users/jgd/.rvm/gems/ruby-2.5.7@rails5.1.7/gems/thor-1.1.0/lib/thor/command.rb:114:in `message'
	 1: from /Users/jgd/.rvm/gems/ruby-2.5.7@rails5.1.7/gems/dead_end-1.1.6/lib/dead_end/auto.rb:69:in `to_s'
/Users/jgd/.rvm/gems/ruby-2.5.7@rails5.1.7/gems/dead_end-1.1.6/lib/dead_end/auto.rb:98:in `rescue in to_s': undefined method `dead_end_original_to_s' for #<ArgumentError: unknown encoding name: Defaults> (NoMethodError)

   65  if !DeadEnd::IsProduction.call
   66    class NoMethodError
   97      rescue => e
❯  98        puts "DeadEnd Internal error: #{e.dead_end_original_to_s}"
  100        puts backtrace.map {|l| "    " + l }.join($/)
  101        super
  102      end
  103    end
  104  end
```

**Comment by josegrad** [comment]
The problem was when using an old version of attr_encrypted gem.
