### ISSUE TITLE
NoMethodError: undefined method `locked_gems' for Bundler:Module

### ISSUE THREAD

**Issue by bcackerman** [schneems/derailed_benchmarks#25]
```
$ rake -f perf.rake perf:require_bench
rake aborted!
NoMethodError: undefined method `locked_gems' for Bundler:Module
/Users/Ackerman/.rvm/gems/ruby-2.0.0-p353/bundler/gems/derailed_benchmarks-36fd32239808/lib/derailed_benchmarks.rb:10:in `gem_is_bundled?'
/Users/Ackerman/.rvm/gems/ruby-2.0.0-p353/bundler/gems/derailed_benchmarks-36fd32239808/lib/derailed_benchmarks/tasks.rb:53:in `block (2 levels) in <top (required)>'
/Users/Ackerman/.rvm/gems/ruby-2.0.0-p353/bin/ruby_executable_hooks:15:in `eval'
/Users/Ackerman/.rvm/gems/ruby-2.0.0-p353/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => perf:require_bench => perf:setup
(See full trace by running task with --trace)
```
Any idea?

**Comment by dman7** [comment]
What version of `bundler` are you using? According to this [commit](https://github.com/bundler/bundler/commit/b89e304cab8c92c969b0a700e5e66c114f23e58d), `locked_gems` method was added in version 1.4.

**Comment by bcackerman** [comment]
bundler (1.3.5).  Let me try to update.

**Comment by bcackerman** [comment]
Thanks @dman7 that worked but now I'm receiving this, any idea?

```
Booting: production
Endpoint: "/"
## Impact of `require <file>` on RAM

Showing all `require <file>` calls that consume 5 mb or more of RSS
Configure with `CUT_OFF=0` for all entries or `CUT_OFF=5` for few entries
Note: Files only count against RAM on their first load.
      If multiple libraries require the same file, then
       the 'cost' only shows up under the first library

rake aborted!
Bad request:         <!DOCTYPE html>
        <html lang="en-US">
          <head><title>301 Moved Permanently</title></head>
          <body>
            <h1>Moved Permanently</h1>
            <p>The document has moved <a href="">here</a>.</p>
          </body>
        </html>
/Users/Ackerman/.rvm/gems/ruby-2.0.0-p353/bundler/gems/derailed_benchmarks-36fd32239808/lib/derailed_benchmarks/tasks.rb:81:in `call_app'
/Users/Ackerman/.rvm/gems/ruby-2.0.0-p353/bundler/gems/derailed_benchmarks-36fd32239808/lib/derailed_benchmarks/tasks.rb:128:in `block (2 levels) in <top (required)>'
/Users/Ackerman/.rvm/gems/ruby-2.0.0-p353/bin/ruby_executable_hooks:15:in `eval'
/Users/Ackerman/.rvm/gems/ruby-2.0.0-p353/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => perf:require_bench
```

**Comment by schneems** [comment]
This

```
 <!DOCTYPE html> <html lang="en-US"> <head><title>301 Moved Permanently</title></head> <body> <h1>Moved Permanently</h1> <p>The document has moved
```

Is indicating that you're not getting a 200 response back. Maybe you're trying to force ssl or redirect to a subdomain.

**Comment by schneems** [comment]
I updated the readme and release a new version of the gem

Can you give it a try again?

**Comment by heartquake** [comment]
I'm getting a similar error when I try "rake build".

I don't know if I'm doing something wrong. Any help would be appreciated.

C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/xbuild-0.2.0/bin/xbuild:3:in `<top (required)>': undefined method `setup' for Bundler:Module (NoMethodError)
