### ISSUE TITLE
Duplicated key error on :service_fee when running bundle exec derailed exec

### ISSUE THREAD

**Issue by tennisonchan** [schneems/derailed_benchmarks#77]
Hello,

When I run the command `bundle exec derailed exec perf:heap` with `USE_SERVER=puma` and here is the errors.

```
Booting: production
/Users/home/Documents/Projects/pistachio/app/models/finance/transactions/name_to_group.rb:4: warning: duplicated key at line 13 ignored: :service_fee
Endpoint: "/"
/Users/home/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/derailed_benchmarks-1.3.1/lib/derailed_benchmarks/tasks.rb:72: warning: already initialized constant DERAILED_APP
/Users/home/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/derailed_benchmarks-1.3.1/lib/derailed_benchmarks/tasks.rb:23: warning: previous definition of DERAILED_APP was here
Running 1000 times
/Users/home/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/derailed_benchmarks-1.3.1/lib/derailed_benchmarks/tasks.rb:92:in `call_app': Bad request:  (RuntimeError)
	from /Users/home/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/derailed_benchmarks-1.3.1/lib/derailed_benchmarks/tasks.rb:275:in `block (3 levels) in <top (required)>'
	from /Users/home/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/derailed_benchmarks-1.3.1/lib/derailed_benchmarks/tasks.rb:274:in `times'
	from /Users/home/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/derailed_benchmarks-1.3.1/lib/derailed_benchmarks/tasks.rb:274:in `block (2 levels) in <top (required)>'
	from /Users/home/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/task.rb:240:in `call'
	from /Users/home/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/task.rb:240:in `block in execute'
	from /Users/home/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/task.rb:235:in `each'
	from /Users/home/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/task.rb:235:in `execute'
	from /Users/home/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
	from /Users/home/.rbenv/versions/2.2.3/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
	from /Users/home/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/task.rb:172:in `invoke_with_call_chain'
	from /Users/home/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/task.rb:165:in `invoke'
	from /Users/home/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/derailed_benchmarks-1.3.1/bin/derailed:41:in `exec'
	from /Users/home/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Users/home/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/home/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /Users/home/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Users/home/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/derailed_benchmarks-1.3.1/bin/derailed:92:in `<top (required)>'
	from /Users/home/.rbenv/versions/2.2.3/bin/derailed:23:in `load'
	from /Users/home/.rbenv/versions/2.2.3/bin/derailed:23:in `<main>'
```

**Comment by tennisonchan** [comment]
It seems I have to load the fixture with the `USE_SERVER=puma`. Thanks for the good work!
