### ISSUE TITLE
NameError: uninitialized constant ActiveRecord

### ISSUE THREAD

**Issue by kkirsche** [schneems/derailed_benchmarks#8]
Hey everyone, I tried to get this to run, specifically I tried to use the `bundle exec rake -f perf.rake perf:require_bench` command but when doing so I get the following:

``` bash
rake aborted!
NameError: uninitialized constant ActiveRecord

Tasks: TOP => perf:require_bench => perf:setup
(See full trace by running task with --trace)
```

When ran with the trace I get:

``` ruby
bundle exec rake -f perf.rake perf:require_bench --trace
** Invoke perf:require_bench (first_time)
** Invoke perf:kernel_require_patch (first_time)
** Execute perf:kernel_require_patch
** Invoke perf:setup (first_time)
** Execute perf:setup
rake aborted!
NameError: uninitialized constant ActiveRecord
/Users/KevinKirsch/.rvm/rubies/ruby-2.1.2/lib/ruby/gems/2.1.0/gems/derailed_benchmarks-0.0.0/lib/derailed_benchmarks/tasks.rb:30:in `block (2 levels) in <top (required)>'
/Users/KevinKirsch/.rvm/rubies/ruby-2.1.2/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib/rake/task.rb:240:in `call'
/Users/KevinKirsch/.rvm/rubies/ruby-2.1.2/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib/rake/task.rb:240:in `block in execute'
/Users/KevinKirsch/.rvm/rubies/ruby-2.1.2/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib/rake/task.rb:235:in `each'
/Users/KevinKirsch/.rvm/rubies/ruby-2.1.2/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib/rake/task.rb:235:in `execute'
/Users/KevinKirsch/.rvm/rubies/ruby-2.1.2/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/Users/KevinKirsch/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/Users/KevinKirsch/.rvm/rubies/ruby-2.1.2/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/Users/KevinKirsch/.rvm/rubies/ruby-2.1.2/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib/rake/task.rb:201:in `block in invoke_prerequisites'
/Users/KevinKirsch/.rvm/rubies/ruby-2.1.2/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib/rake/task.rb:199:in `each'
/Users/KevinKirsch/.rvm/rubies/ruby-2.1.2/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib/rake/task.rb:199:in `invoke_prerequisites'
/Users/KevinKirsch/.rvm/rubies/ruby-2.1.2/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib/rake/task.rb:178:in `block in invoke_with_call_chain'
/Users/KevinKirsch/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/Users/KevinKirsch/.rvm/rubies/ruby-2.1.2/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/Users/KevinKirsch/.rvm/rubies/ruby-2.1.2/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib/rake/task.rb:165:in `invoke'
/Users/KevinKirsch/.rvm/rubies/ruby-2.1.2/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:150:in `invoke_task'
/Users/KevinKirsch/.rvm/rubies/ruby-2.1.2/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/Users/KevinKirsch/.rvm/rubies/ruby-2.1.2/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:106:in `each'
/Users/KevinKirsch/.rvm/rubies/ruby-2.1.2/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:106:in `block in top_level'
/Users/KevinKirsch/.rvm/rubies/ruby-2.1.2/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:115:in `run_with_threads'
/Users/KevinKirsch/.rvm/rubies/ruby-2.1.2/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:100:in `top_level'
/Users/KevinKirsch/.rvm/rubies/ruby-2.1.2/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:78:in `block in run'
/Users/KevinKirsch/.rvm/rubies/ruby-2.1.2/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:176:in `standard_exception_handling'
/Users/KevinKirsch/.rvm/rubies/ruby-2.1.2/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:75:in `run'
/Users/KevinKirsch/.rvm/rubies/ruby-2.1.2/lib/ruby/gems/2.1.0/gems/rake-10.3.2/bin/rake:33:in `<top (required)>'
/Users/KevinKirsch/.rvm/gems/ruby-2.1.2/bin/rake:23:in `load'
/Users/KevinKirsch/.rvm/gems/ruby-2.1.2/bin/rake:23:in `<main>'
Tasks: TOP => perf:require_bench => perf:setup
```

Any suggestions on what I can do to get this to work or to disable it attempting to benchmark ActiveRecord which isn't in use in our application. Thank you for your time, I appreciate your patience.

**Comment by jarthod** [comment]
Is there any plan to release a gem since then ? :)

**Comment by schneems** [comment]
Waiting till I can get my auth patch passing on 2.2 and merged in



—
