### ISSUE TITLE
Benchmarking Sinatra?

### ISSUE THREAD

**Issue by nicatronTg** [schneems/derailed_benchmarks#92]
Okay, so I read https://github.com/schneems/derailed_benchmarks/issues/84 and the readme about how to load an arbitrary Rack app. However, I don't know much about Rack + Sinatra modular apps, or at least, enough on how to load them in derailed.

I'm trying to run ```bundle exec derailed exec perf:mem_over_time``` with the following ```perf.rake```:

```ruby
require 'derailed_benchmarks'
require 'derailed_benchmarks/tasks'

namespace :perf do
  task :rack_load do

    require_relative './Jump'
    DERAILED_APP = Jump.run!
  end
end
```

where ```Jump``` is a modular Sinatra, app, e.g.,

```ruby
require 'sinatra'
require 'newrelic_rpm'
require 'sinatra/partial'
require 'sinatra_more/markup_plugin'
require 'mongoid'
require 'bcrypt'
require 'raven'
require 'skylight/sinatra'
require 'redis'
require 'sidekiq'

class Jump < Sinatra::Base
# snip
end
```

and where the ```config.ru``` is

```
require './Jump'
run Jump
```

If I start it, this happens:

```
$ bundle exec derailed exec perf:mem_over_time

You're not using Rails
You need to tell derailed how to boot your app
In your perf.rake add:

namespace :perf do
  task :rack_load do
    # DERAILED_APP = your code here
  end
end
Jump development server is online.
== Sinatra (v1.4.7) has taken the stage on 4567 for development with backup from Puma
Puma starting in single mode...
* Version 3.6.2 (ruby 2.3.3-p222), codename: Sleepy Sunday Serenity
* Min threads: 0, max threads: 16
* Environment: development
* Listening on tcp://localhost:4567
```

and nothing else unless I hit CTRL + C, at which point it shuts down and I end up with

```
== Sinatra has ended his set (crowd applauds)
- Gracefully stopping, waiting for requests to finish
=== puma shutdown: 2017-01-09 20:21:17 -0700 ===
- Goodbye!
Endpoint: "/"
bundler: failed to load command: derailed (/Users/shank/.rbenv/versions/2.3.3/bin/derailed)
LoadError: cannot load such file -- rack/test
  /Users/shank/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/skylight-1.0.1/lib/skylight/probes.rb:81:in `require'
  /Users/shank/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/skylight-1.0.1/lib/skylight/probes.rb:81:in `require'
  /Users/shank/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/derailed_benchmarks-1.3.1/lib/derailed_benchmarks/tasks.rb:69:in `block (2 levels) in <top (required)>'
  /Users/shank/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rake-11.3.0/lib/rake/task.rb:248:in `block in execute'
  /Users/shank/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rake-11.3.0/lib/rake/task.rb:243:in `each'
  /Users/shank/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rake-11.3.0/lib/rake/task.rb:243:in `execute'
  /Users/shank/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rake-11.3.0/lib/rake/task.rb:187:in `block in invoke_with_call_chain'
  /Users/shank/.rbenv/versions/2.3.3/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
  /Users/shank/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rake-11.3.0/lib/rake/task.rb:180:in `invoke_with_call_chain'
  /Users/shank/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rake-11.3.0/lib/rake/task.rb:209:in `block in invoke_prerequisites'
  /Users/shank/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rake-11.3.0/lib/rake/task.rb:207:in `each'
  /Users/shank/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rake-11.3.0/lib/rake/task.rb:207:in `invoke_prerequisites'
  /Users/shank/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rake-11.3.0/lib/rake/task.rb:186:in `block in invoke_with_call_chain'
  /Users/shank/.rbenv/versions/2.3.3/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
  /Users/shank/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rake-11.3.0/lib/rake/task.rb:180:in `invoke_with_call_chain'
  /Users/shank/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rake-11.3.0/lib/rake/task.rb:173:in `invoke'
  /Users/shank/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/derailed_benchmarks-1.3.1/bin/derailed:41:in `exec'
  /Users/shank/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
  /Users/shank/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
  /Users/shank/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
  /Users/shank/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
  /Users/shank/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/derailed_benchmarks-1.3.1/bin/derailed:92:in `<top (required)>'
  /Users/shank/.rbenv/versions/2.3.3/bin/derailed:22:in `load'
  /Users/shank/.rbenv/versions/2.3.3/bin/derailed:22:in `<top (required)>'
```

How exactly do I properly mount a **modular Sinatra app** using derailed?

**Comment by treble37** [comment]
Do you have a link to the repo of the Sinatra app you are trying to run derailed on?  That would help with duplicating your issue more quickly I think...

**Comment by nicatronTg** [comment]
@treble37 unfortunately, I don't -- it's closed source. I could make a little Sinatra app that demonstrates the problem, if that would help, but I'm honestly just following the Sinatra docs as far as creating **modular** Sinatra apps.

**Comment by treble37** [comment]
@nicatronTg, looking at your error about `LoadError: cannot load such file -- rack/test` - I think you have to install `rack-test`.

Here is a link to the tiny repo I made that shows one possible setup:  https://github.com/treble37/sinatra_with_derailed_example/blob/master/Gemfile#L4

Running `bundle exec derailed exec perf:mem_over_time` yields something like:

You're not using Rails
You need to tell derailed how to boot your app
In your perf.rake add:

```
namespace :perf do
  task :rack_load do
    # DERAILED_APP = your code here
  end
end
Endpoint: "/"
/Users/xxx/.asdf/installs/ruby/2.3.3/lib/ruby/gems/2.3.0/gems/derailed_benchmarks-1.3.2/lib/derailed_benchmarks/tasks.rb:72: warning: already initialized constant DERAILED_APP
/Users/xxx/Documents/code/sinatra_with_derailed_example/perf.rake:10: warning: previous definition of DERAILED_APP was here
PID: 36494
24.23046875
```

Note: I'm not using rbenv but a tool called asdf but I imagine your error is related to a lack of `rack-test`. Hope this helps.

**Comment by nicatronTg** [comment]
@treble37 I think that example is an excellent resource. While missing ```rack-test``` was probably part of it, defining ```DERAILED_APP``` as just the app name (without the ```run!```) directive was probably part of it too.

I'll re-open the issue if I encounter any other weird spots, but thank you! I'm now happily (or unhappily?) debugging a memory leak in a Sinatra app!

Thank you again!!
